export declare const request_api_port = 2121;
export declare var request_api_location: string;
export declare const request_api_location_fetch: string;
export declare const request_api_location_post: string;
export declare const request_post_login: string;
export declare const request_post_timer: string;
export declare const request_post_setup: string;
export declare const request_post_purge: string;
export declare const request_fetch_teams: string;
export declare const request_post_team_score: string;
export declare const request_fetch_event: string;
