### health
GET https://localhost:8080/pulse

###
POST https://localhost:8080/register
Content-Type: application/json

{
}

###
DELETE https://localhost:8080/register/fb1ae42c-4460-44be-bc27-56a6a39fc19f
Content-Type: application/json
X-Client-Id: ba359e64-a2c5-4486-ae07-d4f2ba97b21b
X-Auth-Token: sW75DMbytY9f92eZvsMCO42bTeeXyQ04

{
}


# sW75DMbytY9f92eZvsMCO42bTeeXyQ04
# ba359e64-a2c5-4486-ae07-d4f2ba97b21b
#