import { IEvent } from "@cjms_shared/services";
import { IJudgingSession } from "@cjms_shared/services";
import { IMatch } from "@cjms_shared/services";
import { ITeamScore, ITeam } from "@cjms_shared/services";
export declare function CJMS_FETCH_GENERIC_POST(request: RequestInfo, postData: any, noAlert?: boolean): Promise<Response>;
export declare function CJMS_FETCH_GENERIC_GET(request: any, noAlert?: boolean): Promise<Response>;
export declare function CJMS_REQUEST_LOGIN(credentials: any): Promise<Response>;
export declare function CJMS_POST_TIMER(timerStatus: string): Promise<Response>;
export declare function CJMS_POST_SCORE(teamScore: ITeamScore): Promise<Response>;
export declare function CJMS_REQUEST_TEAMS(noAlert?: boolean): Promise<ITeam[]>;
export declare function CJMS_REQUEST_MATCHES(noAlert?: boolean): Promise<IMatch[]>;
export declare function CJMS_REQUEST_EVENT(noAlert?: boolean): Promise<IEvent>;
export declare function CJMS_REQUEST_JUDGING_SESSIONS(noAlert?: boolean): Promise<IJudgingSession[]>;
