blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/CJBuchel/TMS/discussions
    about: >
      Have a question or need help? Connect on the
      discussion board
